# =============================================================================
# Makefile for the C Text Editor Project
# =============================================================================

# --- Compiler and Flags ---
# Use gcc as the C compiler
CC = gcc
# CFLAGS are the compiler flags.
# -g: Adds debugging information for GDB.
# -Wall: Enables all standard warnings.
# -Wextra: Enables extra (but still useful) warnings.
# -std=c11: Use the C11 standard.
# -Iinclude: Tells the compiler to look for header files in the 'include' directory.
# -MMD -MP: Generates dependency files (.d) to track header changes.
CFLAGS = -g -Wall -Wextra -std=c11 -Iinclude -MMD -MP

# LDFLAGS are the linker flags (none needed for this simple project yet)
LDFLAGS =

# --- Project Structure ---
# Name of the final executable file
TARGET = text_editor

# Directories
BUILD_DIR = build
SRC_DIRS = src/backend src/frontend

# --- Source Files ---
# Automatically find all .c files in the specified source directories
# and also include main.c from the root directory.
SRCS = $(wildcard $(addsuffix /*.c, $(SRC_DIRS))) main.c

# --- Object Files ---
# Generate a list of object file names (.o) that will be placed in the BUILD_DIR.
# This replaces the source directory and .c extension with the build directory and .o extension.
OBJS = $(addprefix $(BUILD_DIR)/, $(notdir $(SRCS:.c=.o)))

# --- Dependency Files ---
# List of dependency files (.d) generated by the -MMD flag
DEPS = $(OBJS:.o=.d)

# =============================================================================
# Main Rules
# =============================================================================

# The '.PHONY' target specifies targets that are not actual files.
# 'all' is the default goal.
.PHONY: all clean run

# Default target: build the executable.
all: $(TARGET)

# Rule to link the final executable.
# It depends on all the object files.
$(TARGET): $(OBJS)
	@echo "Linking executable: $@"
	$(CC) $(LDFLAGS) -o $@ $^

# Rule to compile source files into object files.
# This rule handles sources from any of the specified SRC_DIRS.
# VPATH tells make where to find the source files.
VPATH = $(SRC_DIRS)
$(BUILD_DIR)/%.o: %.c
	@mkdir -p $(@D)
	@echo "Compiling: $<"
	$(CC) $(CFLAGS) -c -o $@ $<

# Include the generated dependency files.
# The '-' before 'include' tells make to not complain if the file doesn't exist.
-include $(DEPS)


# =============================================================================
# Utility Rules
# =============================================================================

# Rule to run the program.
# It first ensures the program is built, then executes it.
run: $(TARGET)
	@echo "--- Running Text Editor ---"
	./$(TARGET)

# Rule to clean the project.
# Removes the executable and the entire build directory.
clean:
	@echo "Cleaning project..."
	rm -f $(TARGET)
	rm -rf $(BUILD_DIR)


